LEXICON = {
    '/start': '<b>Hi</b>👋 \n\n'
            '<b>This is a bot from @R60GB, in which</b>\n'
            '<b>you can purchase different tariff plans</b>\n' 
            '<b>for our VIP channels</b>💞\n\n'
            '<b>as well as familiarize yourself with</b>\n' 
            '<b>the content of VIP channels.</b>\n\n' 
            '<b>You can subscribe to all our channels</b>\n' 
            '<b>to participate in the</b>\n'
            '<b>competition for access to our VIP</b>🫶', 
    '/help':'If you are confused about the functionality of the bot, ' 
            'just restart it with the -> /start ' 
            'command, and then follow the buttons ' 
            'that are attached to the messages\n\n'
            'If you want to buy access to the VIP:\n press -> /pay\n\n'
            'If after paying for access to VIP, ' 
            'for some reason you were not ' 
            'sent a one-time link, or it is '
            'invalid - send a screenshot of the ' 
            'payment to the chat with the bot, ' 
            'in this case it will not be necessary ' 
            'to write to the administrator.\n\n'
            'If you find a bug in the work of ' 
            'our bot, be sure to write to the ' 
            'admin - for this you will receive a reward\n\n'
            'ADMIN - @R60GBadmin', 
   'awesfeet': '<b>FootFetish VIP | R60GB\n\n' 
            '4000+ media\n\n' 
            '60+ Onlyfans&Footfetish Models Leak\n\n'
            'Popular Hashtags: teens, footjob, selfworship, '
            'ballbusting, footgagging, tickling, femdom, bootjob '
            'and 60 hashtags more...\n\n' 
            'You can look at the examples:</b>\n\n'
            'https://t.me/+pKPXSJPKtEE3ZDMy\n\n', 
    'ffanime': '<b>Hentai FootFetish(+18)\n\n'
           'Categories:\n'
           'Loli, Pregnant, SelfWorship, Footjob, Monster, '
           'Socks, Wetfeet, cum on feet, BootJob, 3D, 2D, POV, FemDom '
           'and 50+ tags more\n'
           'You can look at the examples:</b>\n\n'
           'https://t.me/+s8-fSGmvW6E5NTIy\n',
    'ru_pay': '<b>Для оплаты русской картой\n'
           'Необходимо написать администратору -</b> @R60GBadmin\n\n'
           '<b>Цена при переводе повышена - 350 рублей\n\n'
           'Старайтесь экономить своё время и время администратора.\n'
           'Сформулируйте свой вопрос в одном сообщении, это\n'
           'повлияет на скорость ответа на ваш вопрос.</b>', 
    'admin_contact': '<b>Contact for feedback on administration:</b>\n' 
        '@R60GBadmin\n\n'
        '<b>Try to fit the whole point into one message, so the admin will respond faster.</b>'
           } 